### ISSUE TITLE
Nomlash bo'yicha mummobor

### ISSUE THREAD

**Issue by AkhrorSoliev** [Lazizbek010/Udarnik#1]
Ukam bo'ldigan nom qo'ygin

**Comment by Lazizbek010** [comment]
Okey🤔

Shan, 16-apr, 2022, 16:24 Akhror ***@***.***>:

**Comment by Lazizbek010** [comment]
Armiya

**Comment by Lazizbek010** [comment]
Assalomu alaykum ustoz yaxshimisiz


сб, 16 апр. 2022 г. в 19:27, Lazizbek Isaqov <
***@***.***>:
